CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
  , sku SKU UNIQUE NOT NULL
  , name NAME NOT NULL
  , description LONG_TEXT
  , meta_id INTEGER UNIQUE NOT NULL REFERENCES meta(id)
);
