CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
  , key KEY UNIQUE NOT NULL
  , name VARCHAR(250) NOT NULL
  , description TEXT
  , meta_id SMALLINT UNIQUE NOT NULL REFERENCES meta(id)
);
