CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
  , key KEY UNIQUE NOT NULL
  , name NAME NOT NULL
  , description DESCRIPTION
  , meta_id INTEGER UNIQUE NOT NULL REFERENCES meta(id)
);
