ALTER TABLE $RECORDS_TABLE
ADD CONSTRAINT fk_created_by
FOREIGN KEY (created_by)
REFERENCES $USERS_TABLE (id);

ALTER TABLE $RECORDS_TABLE
ADD CONSTRAINT fk_edited_by
FOREIGN KEY (edited_by)
REFERENCES $USERS_TABLE (id);

ALTER TABLE $RECORDS_TABLE
ADD CONSTRAINT fk_deleted_by
FOREIGN KEY (deleted_by)
REFERENCES $USERS_TABLE (id);

ALTER TABLE $RECORDS_TABLE
ADD CONSTRAINT fk_restored_by
FOREIGN KEY (restored_by)
REFERENCES $USERS_TABLE (id);

ALTER TABLE $STAFF_TABLE
ADD CONSTRAINT fk_record_id
FOREIGN KEY (record_id)
REFERENCES $RECORDS_TABLE (id);

ALTER TABLE $STAFF_TABLE
ADD CONSTRAINT fk_person_id
FOREIGN KEY (person_id)
REFERENCES $PEOPLE_TABLE (id);

ALTER TABLE $PATIENTS_TABLE
ADD CONSTRAINT fk_record_id
FOREIGN KEY (record_id)
REFERENCES $RECORDS_TABLE (id);

ALTER TABLE $PATIENTS_TABLE
ADD CONSTRAINT fk_person_id
FOREIGN KEY (person_id)
REFERENCES $PEOPLE_TABLE (id);

ALTER TABLE $STAFF_DEPARTMENTS
ADD CONSTRAINT fk_staff_id
FOREIGN KEY (staff_id)
REFERENCES $STAFF_TABLE (id);

ALTER TABLE $STAFF_DEPARTMENTS
ADD CONSTRAINT fk_department_id
FOREIGN KEY (department_id)
REFERENCES $DEPARTMENTS_TABLE (id);

ALTER TABLE $VISITS_TABLE
ADD CONSTRAINT fk_patient_id
FOREIGN KEY (patient_id)
REFERENCES $PATIENTS_TABLE (id);

ALTER TABLE $VISITS_TABLE
ADD CONSTRAINT fk_staff_id
FOREIGN KEY (staff_id)
REFERENCES $STAFF_TABLE (id);

ALTER TABLE $USERS_TABLE
ADD CONSTRAINT fk_${RECORDS_TABLE}
FOREIGN KEY (record_id)
REFERENCES $RECORDS_TABLE (id);

ALTER TABLE $USERS_TABLE
ADD CONSTRAINT fk_${STAFF_TABLE}
FOREIGN KEY (staff_id)
REFERENCES $STAFF_TABLE (id);
