#!/bin/bash

psql << EOF

DROP DATABASE IF EXISTS $ABBREVIATION;
CREATE DATABASE $ABBREVIATION;

CREATE TABLE $SEX_NAME (
    user_id serial PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

EOF
